<tr class="color_row">
    <th colspan="5">105/04 現金XXX元</th>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>
<tr>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
    <td>XXX</td>
</tr>